[package]
name = "rust_notes"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = "0.30.0"
color-eyre = "0.6.3"
crossterm = "0.29.0"
edtui = "0.11.1"
tui-tree-widget = "0.24.0"
termimad = "0.34.1"
